Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -74,6 +74,10 @@ jobs:
         id: bump_version
         run: |
           current_version=$(grep -oP '^set\s*\(\s*PROJECT_VERSION\s+\K\d+\.\d+\.\d+' CMakeLists.txt) # Extract current version from CMakeLists.txt
+          if [ -z "$current_version" ]; then
+            echo "Error: Unable to extract current version from CMakeLists.txt"
+            exit 1
+          fi
           major=$(echo $current_version | cut -d '.' -f 1) # Extract major version
           minor=$(echo $current_version | cut -d '.' -f 2) # Extract minor version
           patch=$(echo $current_version | cut -d '.' -f 3) # Extract patch version
